// Random questions data for waiting state
// Add more questions here as needed

export interface RandomQuestion {
  type: "multiple" | "boolean";
  difficulty: "easy" | "medium" | "hard";
  category: string;
  question: string;
  correct_answer: string;
  incorrect_answers: string[];
}

export const RANDOM_QUESTIONS: RandomQuestion[] = [
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Television", "question": "What breed of dog is &quot;Scooby Doo&quot;?", "correct_answer": "Great Dane", "incorrect_answers": ["Pit bull", "Boxer", "Doberman Pinscher"]},
  {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Books", "question": "Which author and poet famously wrote the line, &quot;The female of the species is more deadly than the male&quot;?", "correct_answer": "Rudyard Kipling", "incorrect_answers": ["Edgar Allan Poe", "William Shakespeare", "William Wordsworth"]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations", "question": "Adam West was the mayor of which cartoon town?", "correct_answer": "Quahog", "incorrect_answers": ["Springfield", "South Park", "Langley Falls"]},
  {"type": "multiple", "difficulty": "medium", "category": "History", "question": "What happened on June 6, 1944?", "correct_answer": "D-Day", "incorrect_answers": ["Atomic bombings of Hiroshima and Nagasaki", "Attack on Pearl Harbor", "The Liberation of Paris"]},
  {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Board Games", "question": "&quot;Rich Uncle Pennybags&quot; from the board game &quot;Monopoly&quot; wears a monocle.", "correct_answer": "False", "incorrect_answers": ["True"]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Musicals &amp; Theatres", "question": "The World Chess Championship in Chess, Act 1 is set in which Italian city?", "correct_answer": "Merano", "incorrect_answers": ["Venice", "Milan", "Rome"]},
  {"type": "multiple", "difficulty": "easy", "category": "Science &amp; Nature", "question": "Which gas forms about 78% of the Earth&rsquo;s atmosphere?", "correct_answer": "Nitrogen", "incorrect_answers": ["Oxygen", "Argon", "Carbon Dioxide"]},
  {"type": "multiple", "difficulty": "easy", "category": "Science: Mathematics", "question": "What prime number comes next after 19?", "correct_answer": "23", "incorrect_answers": ["25", "21", "27"]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games", "question": "Which of these games was the earliest known first-person shooter with a known time of publication?", "correct_answer": "Spasim", "incorrect_answers": ["Doom", "Wolfenstein", "Quake"]},
  {"type": "multiple", "difficulty": "easy", "category": "Celebrities", "question": "Neil Hamburger is played by which comedian?", "correct_answer": "Gregg Turkington", "incorrect_answers": ["Nathan Fielder", "Tim Heidecker", "Todd Glass"]},
  {"type": "multiple", "difficulty": "easy", "category": "General Knowledge", "question": "When someone is inexperienced they are said to be what color?", "correct_answer": "Green", "incorrect_answers": ["Red", "Blue", "Yellow"]},
  {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television", "question": "In &quot;Star Trek&quot;, Klaang is a typical Klingon male.", "correct_answer": "True", "incorrect_answers": ["False"]},
  {"type": "multiple", "difficulty": "medium", "category": "History", "question": "Who was the first president born in the independent United States?", "correct_answer": "Martin Van Buren", "incorrect_answers": ["John Adams", "George Washington", "James Monroe "]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Books", "question": "What was the last message of the Dolphins in &quot;The Hitchhiker&#039;s Guide to the Galaxy&quot;?", "correct_answer": "&quot;So long, and thanks for all the fish.&quot;", "incorrect_answers": ["&quot;The answer is 42.&quot;", "&quot;Land of the brave.&quot;", "&quot;Goodbye cruel world!&quot;"]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games", "question": "In which Mario game did the Mega Mushroom make its debut?", "correct_answer": "Mario Party 4", "incorrect_answers": ["New Super Mario Bros.", "Mario Kart Wii", "Super Mario 3D World"]},
  {"type": "multiple", "difficulty": "hard", "category": "Animals", "question": "Which of these is a colony of polyps and not a jellyfish?", "correct_answer": "Portuguese Man-of-War", "incorrect_answers": ["Sea Wasp", "Irukandji", "Sea Nettle"]},
  {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film", "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.", "correct_answer": "False", "incorrect_answers": ["True"]},
  {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.", "correct_answer": "True", "incorrect_answers": ["False"]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Music", "question": "Which of the following is NOT a song in BROCKHAMPTON&#039;s SATURATION album series?", "correct_answer": "LAMB", "incorrect_answers": ["HOTTIE", "SWAMP", "BUMP"]},
  {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games", "question": "What was the name of the cancelled sequel of Team Fortress?", "correct_answer": "Team Fortress 2: Brotherhood of Arms", "incorrect_answers": ["Team Fortress 2: Desert Mercenaries", "Team Fortress 2: Operation Gear Grinder", "Team Fortress 2: Return to Classic"]},
  {"type": "multiple", "difficulty": "medium", "category": "Art", "question": "Who designed the Chupa Chups logo?", "correct_answer": "Salvador Dali", "incorrect_answers": ["Pablo Picasso", "Andy Warhol", "Vincent van Gogh"]},
  {"type": "multiple", "difficulty": "medium", "category": "Science: Computers", "question": "The teapot often seen in many 3D modeling applications is called what?", "correct_answer": "Utah Teapot", "incorrect_answers": ["Pixar Teapot", "3D Teapot", "Tennessee Teapot"]},
  {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games", "question": "In &quot;Undertale&quot;, the main character of the game is Sans.", "correct_answer": "False", "incorrect_answers": ["True"]},
  {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music", "question": "A Saxophone is a brass instrument.", "correct_answer": "False", "incorrect_answers": ["True"]},
  {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games", "question": "What is Gabe Newell&#039;s favorite class in Team Fortress 2?", "correct_answer": "Spy", "incorrect_answers": ["Heavy", "Medic", "Pyro"]},
  {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Film", "question": "Who directed the movies &quot;Pulp Fiction&quot;, &quot;Reservoir Dogs&quot; and &quot;Django Unchained&quot;?", "correct_answer": "Quentin Tarantino", "incorrect_answers": ["Martin Scorcese", "Steven Spielberg", "James Cameron"]},
  {"type": "multiple", "difficulty": "medium", "category": "General Knowledge", "question": "After how many years would you celebrate your crystal anniversary?", "correct_answer": "15", "incorrect_answers": ["20", "10", "25"]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games", "question": "The mobile game &quot;Jetpack Joyride&quot; was released in what year? ", "correct_answer": "2011", "incorrect_answers": ["2012", "2009", "2014"]},
  {"type": "multiple", "difficulty": "easy", "category": "Geography", "question": "Which nation claims ownership of Antarctica?", "correct_answer": "No one, but there are claims.", "incorrect_answers": ["United States of America", "United Nations", "Australia"]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations", "question": "What is the name of the Alligator that The Simpsons &quot;killed&quot; in the episode &quot;Kill The Alligator and Run&quot;?", "correct_answer": "Captain Jack", "incorrect_answers": ["Captain Jake", "Captain Hector", "Captain Flynn"]},
  {"type": "boolean", "difficulty": "hard", "category": "History", "question": "Joseph Stalin&#039;s real name was Ioseb Bessarionis dze Dzugashvili.", "correct_answer": "True", "incorrect_answers": ["False"]},
  {"type": "multiple", "difficulty": "easy", "category": "Sports", "question": "Which country hosted the 2020 Summer Olympics?", "correct_answer": "Japan", "incorrect_answers": ["China", "Australia", "Germany"]},
  {"type": "multiple", "difficulty": "hard", "category": "Animals", "question": "What scientific suborder does the family Hyaenidae belong to?", "correct_answer": "Feliformia", "incorrect_answers": ["Haplorhini", "Caniformia", "Ciconiiformes"]},
  {"type": "multiple", "difficulty": "hard", "category": "Geography", "question": "In 2012 the German-speaking microstate &quot;Liechtenstein&quot; in Central Europe had a population of how many inhabitants?", "correct_answer": "36,600", "incorrect_answers": ["2,400", "90,000", "323,400"]},
  {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film", "question": "Brandon Routh plays the titular character in the movie &quot;John Wick&quot;.", "correct_answer": "False", "incorrect_answers": ["True"]},
  {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Film", "question": "Which 1994 film did Roger Ebert famously despise, saying &quot;I hated hated hated hated hated this movie&quot;.", "correct_answer": "North", "incorrect_answers": ["3 Ninjas Kick Back", "The Santa Clause", "Richie Rich"]},
  {"type": "multiple", "difficulty": "easy", "category": "Vehicles", "question": "Which of the following collision avoidance systems helps airplanes avoid colliding with each other?", "correct_answer": "TCAS", "incorrect_answers": ["GPWS", "OCAS", "TAWS"]},
  {"type": "multiple", "difficulty": "medium", "category": "Science &amp; Nature", "question": "Where did the Great Storm of 1987 make landfall at, first?", "correct_answer": "Cornwall", "incorrect_answers": ["Surrey", "Wales", "The Midlands"]},
  {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Film", "question": "Where does the original Friday The 13th movie take place?", "correct_answer": "Camp Crystal Lake", "incorrect_answers": ["Packanack", "Higgins Haven", "Camp Forest Green"]},
  {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Television", "question": "What TV show is about a grandfather dragging his grandson around on adventures?", "correct_answer": "Rick &amp; Morty", "incorrect_answers": ["Family Guy", "South Park", "American Dad"]},
  {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Musicals &amp; Theatres", "question": "Which Shakespeare play inspired the musical &#039;West Side Story&#039;?", "correct_answer": "Romeo &amp; Juliet", "incorrect_answers": ["Hamlet", "Macbeth", "Othello"]},
  {"type": "multiple", "difficulty": "medium", "category": "History", "question": "Which country gifted the Statue of Liberty to the United States of America?", "correct_answer": "France", "incorrect_answers": ["Spain", "England", "Germany"]},
  {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga", "question": "The two main characters of &quot;No Game No Life&quot;, Sora and Shiro, together go by what name?", "correct_answer": "Blank", "incorrect_answers": ["Immanity", "Disboard", "Warbeasts"]},
  {"type": "multiple", "difficulty": "medium", "category": "General Knowledge", "question": "Apple co-founder Steve Jobs died from complications of which form of cancer?", "correct_answer": "Pancreatic", "incorrect_answers": ["Bone", "Liver", "Stomach"]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games", "question": "Which of these is not a playable character in &quot;Enter The Gungeon?&quot;", "correct_answer": "The Heavy", "incorrect_answers": ["The Bullet", "The Robot", "The Cultist"]},
  {"type": "multiple", "difficulty": "medium", "category": "Geography", "question": "Which country has the abbreviation &quot;CH&quot;?", "correct_answer": "Switzerland", "incorrect_answers": ["China", "Canada", "No Country"]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Television", "question": "In &quot;Spongebob Squarepants,&quot; what is Mr. Krabs&#039; full name?", "correct_answer": "Eugene H. Krabs", "incorrect_answers": ["Eugene G. Krabs", "Eugene J. Krabs", "Eugene D. Krabs"]},
  {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Film", "question": "In the &quot;Jurassic Park&quot; universe, what is the name of the island that contains InGen&#039;s Site B?", "correct_answer": "Isla Sorna", "incorrect_answers": ["Isla Nublar", "Isla Pena", "Isla Muerta"]},
  {"type": "multiple", "difficulty": "hard", "category": "Entertainment: Video Games", "question": "Where are Terror Fiends more commonly found in the Nintendo game Miitopia?", "correct_answer": "New Lumos", "incorrect_answers": ["Peculia", "The Sky Scraper", "Otherworld"]},
  {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Video Games", "question": "In Super Mario Bros., who informs Mario that the princess is in another castle?", "correct_answer": "Toad", "incorrect_answers": ["Luigi", "Yoshi", "Bowser"]}
];


